//-----------------------------------------------------------------------------
//  Platformer Starter Kit
//  Copyright (C) Phillip O'Shea
//  
//  Platformer Art - All of the art used in the PSK Demo
//-----------------------------------------------------------------------------

// Create Resource Descriptor
$instantResource = new ScriptObject()
{
   Class			   = "PlatformerArt";
   Name				= "PlatformerArt";
   User				= "TGB";
   LoadFunction	= "PlatformerArt::LoadResource";
   UnloadFunction	= "PlatformerArt::UnloadResource";
};

// Load Resource Function
function PlatformerArt::LoadResource( %this )
{
	
}

// Unload Resource Function
function PlatformerArt::UnloadResource( %this )
{
   // Remove all of the objects we use
   if( isObject( %this.Data ) && %this.Data.GetCount() > 0 )
   {      
      while( %this.Data.getCount() > 0 )
      {
         %datablockObj = %this.Data.getObject( 0 );
         %this.Data.remove( %datablockObj );
         if( isObject( %datablockObj ) )
            %datablockObj.delete();
      }
   }
}

// Resource Data
$instantResource.Data = new SimGroup() 
{
   //---------------------------------------------------------------------------
   // Audio Datablocks
   //---------------------------------------------------------------------------
   new AudioDescription(SoundOnce)
   {
      volume		= 1.0;
      type		   = 0;
      isLooping	= false;
      is3D		   = false;
   };

   new AudioDescription(SoundLoop)
   {
      volume		= 1.0;
      type		   = 0;
      isLooping	= true;
      is3D		   = false;
   };

   new AudioDescription(MusicLoop)
   {
      volume		= 1.0;
      type		   = 1;
      isLooping	= true;
      is3D		   = false;
   };

   new AudioProfile(DragonSpawnSound0)
   {
      filename	   = "./data/audio/dragon/startup 1a.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DragonSpawnSound1)
   {
      filename	   = "./data/audio/dragon/startup 1b.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DragonRunSound0)
   {
      filename	   = "./data/audio/dragon/grass_step1.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DragonRunSound1)
   {
      filename	   = "./data/audio/dragon/grass_step2.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DragonRunSound2)
   {
      filename	   = "./data/audio/dragon/grass_step3.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DragonSlideSound)
   {
      filename	   = "./data/audio/dragon/slide.wav";
      description = "SoundLoop";
      preload 	   = true;
   };

   new AudioProfile(DragonJumpSound)
   {
      filename	   = "./data/audio/dragon/jump.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DragonLandSound)
   {
      filename	   = "./data/audio/dragon/land.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DragonDamageSound)
   {
      filename	   = "./data/audio/dragon/ouch.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DragonDieSound0)
   {
      filename	   = "./data/audio/dragon/die 1.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DragonDieSound1)
   {
      filename	   = "./data/audio/dragon/die 2.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DragonClimbUpSound)
   {
      filename	   = "./data/audio/dragon/rope_climb.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DragonClimbDownSound)
   {
      filename	   = "./data/audio/dragon/rope_slide.wav";
      description = "SoundLoop";
      preload 	   = true;
   };

   new AudioProfile(DrillDieSound)
   {
      filename	   = "./data/audio/drill/drill_dies.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(DrillIdleSound)
   {
      filename	   = "./data/audio/drill/drill_motor_loop.wav";
      description = "SoundLoop";
      preload 	   = true;
   };

   new AudioProfile(PepperPickupSound)
   {
      filename	   = "./data/audio/general/pepper_pickup.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(CheckPointPickupSound)
   {
      filename	   = "./data/audio/general/checkpoint_reached.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(MushroomBounceSound)
   {
      filename	   = "./data/audio/dragon/land_mushroom.wav";
      description = "SoundOnce";
      preload 	   = true;
   };

   new AudioProfile(IndoorMusic)
   {
      filename	   = "./data/audio/music/indoor_music.wav";
      description	= MusicLoop;
      preload		= true;
      
      Alternate	= "OutdoorMusic";
   };

   new AudioProfile(OutdoorMusic)
   {
      filename	   = "./data/audio/music/outdoor_music.wav";
      description	= MusicLoop;
      preload		= true;
      
      Alternate	= "IndoorMusic";
   };

   new AudioProfile(LevelCompleteMusic)
   {
      filename    = "./data/audio/music/finish_level_loop.wav";
      description	= MusicLoop;
      preload		= true;
   };
   
   //---------------------------------------------------------------------------
   // Graphics
   //---------------------------------------------------------------------------
   new t2dImageMapDatablock(DragonBlinkImagemap) {
		imageName = "./data/images/Actor/blink.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonActionAnimation) {
      imageMap = "DragonBlinkImagemap";
      animationFrames = "0";
      animationTime = "0.0333333";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonClimbImageMap) {
      imageName = "./data/images/Actor/Climb.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonClimbupAnimation) {
      imageMap = "DragonClimbImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10 11";
      animationTime = "0.6";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
         stepFrames = "5 11";
   };
   new t2dImageMapDatablock(DragonClimb_to_ClimbIdleImageMap) {
      imageName = "./data/images/Actor/Climb_to_ClimbIdle.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonClimbDown_to_ClimbIdleAnimation) {
      imageMap = "DragonClimb_to_ClimbIdleImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.25";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(DragonClimbUp_to_ClimbIdleAnimation) {
      imageMap = "DragonClimb_to_ClimbIdleImageMap";
      animationFrames = "2";
      animationTime = "0.0333333";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonClimbIdleImageMap) {
      imageName = "./data/images/Actor/ClimbIdle.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonClimbIdleAnimation) {
      imageMap = "DragonClimbIdleImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.3";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonFallImageMap) {
      imageName = "./data/images/Actor/Fall.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonFallAnimation) {
      imageMap = "DragonFallImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.15";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonFlyImageMap) {
      imageName = "./data/images/Actor/fly.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonGlideAnimation) {
      imageMap = "DragonFlyImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8";
      animationTime = "0.45";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonDieImageMap) {
      imageName = "./data/images/Actor/die.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonDieAnimation) {
      imageMap = "DragonDieImageMap";
      animationFrames = "0 1 2 3 4";
      animationTime = "0.416667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonIdleImageMap) {
      imageName = "./data/images/Actor/Idle.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonIdleAnimation) {
      imageMap = "DragonIdleImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10 11";
      animationTime = "0.4";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonJumpImageMap) {
      imageName = "./data/images/Actor/Jump.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonJumpAnimation) {
      imageMap = "DragonJumpImageMap";
      animationFrames = "1";
      animationTime = "0.05";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonJump_to_FallImageMap) {
      imageName = "./data/images/Actor/Jump_to_Fall.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonJump_to_FallAnimation) {
      imageMap = "DragonJump_to_FallImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.25";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(DragonRun_to_FallAnimation) {
      imageMap = "DragonJump_to_FallImageMap";
      animationFrames = "1 1 2";
      animationTime = "0.25";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(DragonFall_to_LandAnimation) {
      imageMap = "DragonJump_to_FallImageMap";
      animationFrames = "2 1";
      animationTime = "0.166667";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(DragonrunJump_to_RunFallAnimation) {
      imageMap = "DragonJump_to_FallImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.25";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(DragonClimbJump_to_FallAnimation) {
      imageMap = "DragonJump_to_FallImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.25";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(DragonClimbJump_to_RunFallAnimation) {
      imageMap = "DragonJump_to_FallImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.25";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonLandImageMap) {
      imageName = "./data/images/Actor/land.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonFall_to_RunAnimation) {
      imageMap = "DragonLandImageMap";
      animationFrames = "0";
      animationTime = "0.0333333";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(DragonFall_to_IdleAnimation) {
      imageMap = "DragonLandImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.15";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(DragonLandAnimation) {
      imageMap = "DragonLandImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.375";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonRunImageMap) {
      imageName = "./data/images/Actor/run.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonRunAnimation) {
      imageMap = "DragonRunImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10 11";
      animationTime = "0.6";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      stepFrames = "5 11";
   };
   new t2dImageMapDatablock(DragonRun_to_SlideImageMap) {
      imageName = "./data/images/Actor/Run_to_Slide.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonRun_to_SlideAnimation) {
      imageMap = "DragonRun_to_SlideImageMap";
      animationFrames = "0";
      animationTime = "0.0333333";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonSlideImageMap) {
      imageName = "./data/images/Actor/Slide.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonSlideAnimation) {
      imageMap = "DragonSlideImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.25";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonSlide_to_IdleImageMap) {
      imageName = "./data/images/Actor/Slide_to_Idle.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonSlide_to_IdleAnimation) {
      imageMap = "DragonSlide_to_IdleImageMap";
      animationFrames = "0 1 2 3 4 5 6 7";
      animationTime = "0.4";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonClimbDownImageMap) {
      imageName = "./data/images/Actor/SlideDown.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonClimbDownAnimation) {
      imageMap = "DragonClimbDownImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.15";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonSpawnImageMap) {
      imageName = "./data/images/Actor/Spawn.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonSpawnAnimation) {
      imageMap = "DragonSpawnImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17";
      animationTime = "0.9";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DragonDamageImageMap) {
      imageName = "./data/images/Actor/damage.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "170";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DragonDamageAnimation) {
      imageMap = "DragonDamageImageMap";
      animationFrames = "0 1 2 3 4";
      animationTime = "0.25";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DrillDieImageMap) {
      imageName = "./data/images/Drill/Drill_Die.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "128";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DrillDieAnimation) {
      imageMap = "DrillDieImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DrillFallImageMap) {
      imageName = "./data/images/Drill/Drill_Fall.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "128";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DrillFallAnimation) {
      imageMap = "DrillFallImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10 11";
      animationTime = "0.4";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DrillFall_to_IdleImageMap) {
      imageName = "./data/images/Drill/Drill_Fall_to_roll.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "128";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DrillFall_to_IdleAnimation) {
      imageMap = "DrillFall_to_IdleImageMap";
      animationFrames = "0 1 2 3";
      animationTime = "0.333333";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(DrillRollImageMap) {
      imageName = "./data/images/Drill/Drill_roll.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "170";
      cellHeight = "128";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(DrillIdleAnimation) {
      imageMap = "DrillRollImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10 11";
      animationTime = "0.4";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(grass_b1ImageMap) {
      imageName = "./data/images/Enviro/grass_b1.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_b2ImageMap) {
      imageName = "./data/images/Enviro/grass_b2.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_blImageMap) {
      imageName = "./data/images/Enviro/grass_bl.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_bl_undercutImageMap) {
      imageName = "./data/images/Enviro/grass_bl_undercut.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_brImageMap) {
      imageName = "./data/images/Enviro/grass_br.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_br_undercutImageMap) {
      imageName = "./data/images/Enviro/grass_br_undercut.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_float_lImageMap) {
      imageName = "./data/images/Enviro/grass_float_l.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_float_rImageMap) {
      imageName = "./data/images/Enviro/grass_float_r.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_float_t1ImageMap) {
      imageName = "./data/images/Enviro/grass_float_t1.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_lImageMap) {
      imageName = "./data/images/Enviro/grass_l.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_l_curveImageMap) {
      imageName = "./data/images/Enviro/grass_l_curve.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_l_slopeImageMap) {
      imageName = "./data/images/Enviro/grass_l_slope.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_rImageMap) {
      imageName = "./data/images/Enviro/grass_r.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_r_curveImageMap) {
      imageName = "./data/images/Enviro/grass_r_curve.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_r_slopeImageMap) {
      imageName = "./data/images/Enviro/grass_r_slope.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_t1ImageMap) {
      imageName = "./data/images/Enviro/grass_t1.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_t2ImageMap) {
      imageName = "./data/images/Enviro/grass_t2.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_tlImageMap) {
      imageName = "./data/images/Enviro/grass_tl.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_tl_cornerImageMap) {
      imageName = "./data/images/Enviro/grass_tl_corner.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_trImageMap) {
      imageName = "./data/images/Enviro/grass_tr.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_tr_cornerImageMap) {
      imageName = "./data/images/Enviro/grass_tr_corner.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_wall_lImageMap) {
      imageName = "./data/images/Enviro/grass_wall_l.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(grass_wall_rImageMap) {
      imageName = "./data/images/Enviro/grass_wall_r.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(w_blankImageMap) {
      imageName = "./data/images/Enviro/w_blank.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(w_detail1ImageMap) {
      imageName = "./data/images/Enviro/w_detail1.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(w_detail2ImageMap) {
      imageName = "./data/images/Enviro/w_detail2.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(w_detail3ImageMap) {
      imageName = "./data/images/Enviro/w_detail3.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(w_detail4ImageMap) {
      imageName = "./data/images/Enviro/w_detail4.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(w_detail5ImageMap) {
      imageName = "./data/images/Enviro/w_detail5.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_b1ImageMap) {
      imageName = "./data/images/Enviro/cave_b1.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_b2ImageMap) {
      imageName = "./data/images/Enviro/cave_b2.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_blImageMap) {
      imageName = "./data/images/Enviro/cave_bl.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_bl_cornerImageMap) {
      imageName = "./data/images/Enviro/cave_bl_corner.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_bl_slopeImageMap) {
      imageName = "./data/images/Enviro/cave_bl_slope.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_brImageMap) {
      imageName = "./data/images/Enviro/cave_br.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_br_cornerImageMap) {
      imageName = "./data/images/Enviro/cave_br_corner.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_br_slopeImageMap) {
      imageName = "./data/images/Enviro/cave_br_slope.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_lImageMap) {
      imageName = "./data/images/Enviro/cave_l.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_rImageMap) {
      imageName = "./data/images/Enviro/cave_r.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_t1ImageMap) {
      imageName = "./data/images/Enviro/cave_t1.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_t2ImageMap) {
      imageName = "./data/images/Enviro/cave_t2.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_tlImageMap) {
      imageName = "./data/images/Enviro/cave_tl.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_tl_cornerImageMap) {
      imageName = "./data/images/Enviro/cave_tl_corner.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_tl_slopeImageMap) {
      imageName = "./data/images/Enviro/cave_tl_slope.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_trImageMap) {
      imageName = "./data/images/Enviro/cave_tr.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_tr_cornerImageMap) {
      imageName = "./data/images/Enviro/cave_tr_corner.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(cave_tr_slopeImageMap) {
      imageName = "./data/images/Enviro/cave_tr_slope.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(transition_grass_cave_tImageMap) {
      imageName = "./data/images/Enviro/transition_grass_cave_t.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(transition_grass_cave_tlImageMap) {
      imageName = "./data/images/Enviro/transition_grass_cave_tl.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_blImageMap) {
      imageName = "./data/images/Enviro/wood_bl.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_bmImageMap) {
      imageName = "./data/images/Enviro/wood_bm.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_brImageMap) {
      imageName = "./data/images/Enviro/wood_br.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_float_lImageMap) {
      imageName = "./data/images/Enviro/wood_float_l.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_float_rImageMap) {
      imageName = "./data/images/Enviro/wood_float_r.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_intersectionImageMap) {
      imageName = "./data/images/Enviro/wood_intersection.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_s1ImageMap) {
      imageName = "./data/images/Enviro/wood_s1.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_s2ImageMap) {
      imageName = "./data/images/Enviro/wood_s2.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_sbImageMap) {
      imageName = "./data/images/Enviro/wood_sb.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_stImageMap) {
      imageName = "./data/images/Enviro/wood_st.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_t1ImageMap) {
      imageName = "./data/images/Enviro/wood_t1.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_t2ImageMap) {
      imageName = "./data/images/Enviro/wood_t2.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_tlImageMap) {
      imageName = "./data/images/Enviro/wood_tl.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(wood_trImageMap) {
      imageName = "./data/images/Enviro/wood_tr.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_boltImageMap) {
      imageName = "./data/images/Misc/stuff_bolt.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_boltplateImageMap) {
      imageName = "./data/images/Misc/stuff_boltplate.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_largeboardImageMap) {
      imageName = "./data/images/Misc/stuff_largeboard.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_smallboardImageMap) {
      imageName = "./data/images/Misc/stuff_smallboard.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(elevator_bottomImageMap) {
      imageName = "./data/images/Misc/elevator_bottom.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(elevator_gearImageMap) {
      imageName = "./data/images/Misc/elevator_gear.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(elevator_RopeImageMap) {
      imageName = "./data/images/Misc/elevator_Rope.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(sky_duskImageMap) {
      imageName = "./data/images/Enviro/sky_dusk.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(sky_caveImageMap) {
      imageName = "./data/images/Background/sky_cave.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(sky_cave_bImageMap) {
      imageName = "./data/images/Background/sky_cave_b.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(sky_cave_tImageMap) {
      imageName = "./data/images/Background/sky_cave_t.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(water_bImageMap) {
      imageName = "./data/images/Enviro/water_b.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(water_btImageMap) {
      imageName = "./data/images/Enviro/water_bt.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(water_ftImageMap) {
      imageName = "./data/images/Enviro/water_ft.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(water_fImageMap) {
      imageName = "./data/images/Enviro/water_f.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(rope_bImageMap) {
      imageName = "./data/images/Misc/rope_b.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(rope_mImageMap) {
      imageName = "./data/images/Misc/rope_m.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(rope_tImageMap) {
      imageName = "./data/images/Misc/rope_t.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(scroll_hillsImageMap) {
      imageName = "./data/images/Background/scroll_hills.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(scroll_mountainsImageMap) {
      imageName = "./data/images/Background/scroll_mountains.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(parallax_caveImageMap) {
      imageName = "./data/images/Background/parallax_cave.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_tree1ImageMap) {
      imageName = "./data/images/Misc/stuff_tree1.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_tree2ImageMap) {
      imageName = "./data/images/Misc/stuff_tree2.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_tree3ImageMap) {
      imageName = "./data/images/Misc/stuff_tree3.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_tree4ImageMap) {
      imageName = "./data/images/Misc/stuff_tree4.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_cloud1ImageMap) {
      imageName = "./data/images/Misc/stuff_cloud1.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_cloud2ImageMap) {
      imageName = "./data/images/Misc/stuff_cloud2.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_cloud3ImageMap) {
      imageName = "./data/images/Misc/stuff_cloud3.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_cloud4ImageMap) {
      imageName = "./data/images/Misc/stuff_cloud4.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_cave_entraceImageMap) {
      imageName = "./data/images/Misc/stuff_cave_entrace.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_stalag1ImageMap) {
      imageName = "./data/images/Misc/stuff_stalag1.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_stalag2ImageMap) {
      imageName = "./data/images/Misc/stuff_stalag2.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(stuff_stalag3ImageMap) {
      imageName = "./data/images/Misc/stuff_stalag3.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(conveyorImageMap) {
      imageName = "./data/images/Misc/conveyor.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "150";
      cellHeight = "150";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(leftConveyorAnimation) {
      imageMap = "conveyorImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8";
      animationTime = "0.3";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(middleConveyorAnimation) {
      imageMap = "conveyorImageMap";
      animationFrames = "9 10 11 12 13 14 15 16 17";
      animationTime = "0.3";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(rightConveyorAnimation) {
      imageMap = "conveyorImageMap";
      animationFrames = "18 19 20 21 22 24 24 25 26";
      animationTime = "0.3";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(platform_crumbleImageMap) {
      imageName = "./data/images/Misc/platform_crumble.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "256";
      cellHeight = "64";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(platform_crumbleAnimation) {
      imageMap = "platform_crumbleImageMap";
      animationFrames = "0 2 4 6 8 10 12";
      animationTime = "0.583333";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(platform_reformAnimation) {
      imageMap = "platform_crumbleImageMap";
      animationFrames = "13 11 9 7 5 3 1";
      animationTime = "0.583333";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(stuff_mushroomImageMap) {
      imageName = "./data/images/Misc/stuff_mushroom.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "128";
      cellHeight = "128";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(yummy_pepperImageMap) {
      imageName = "./data/images/Misc/yummy_pepper.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "64";
      cellHeight = "64";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(yummy_pepperAnimation) {
      imageMap = "yummy_pepperImageMap";
      animationFrames = "0 1 2 3 4 5 4 3 2 1";
      animationTime = "0.666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(mushroomBounceAnimation) {
      imageMap = "stuff_mushroomImageMap";
      animationFrames = "0 1 2 3 4 5 4 3 2 1 0";
      animationTime = "0.5";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(eggImageMap) {
      imageName = "./data/images/misc/egg.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "60";
      cellHeight = "72";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(eggAnimation) {
      imageMap = "eggImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(goldeggImageMap) {
      imageName = "./data/images/misc/goldegg.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "58";
      cellHeight = "69";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(goldeggAnimation) {
      imageMap = "goldeggImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(congratulationsImageMap) {
      imageName = "./data/images/gui/HUD_congratulations.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "512";
      cellHeight = "64";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(congratulationsAnimation) {
      imageMap = "congratulationsImageMap";
      animationFrames = "0 1 2 3";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(HUD_gameoverImageMap) {
      imageName = "./data/images/GUI/HUD_gameover.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "380";
      cellHeight = "64";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(HUD_gameoverAnimation) {
      imageMap = "HUD_gameoverImageMap";
      animationFrames = "0 1";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
   };
};